/**
 * AWS Services Registry for Cloud Academy Diagram Builder
 * 
 * Defines all AWS services available for drag-drop architecture diagrams.
 * Uses Lucide icons as fallback - can be extended with official AWS SVGs later.
 */

export type AWSCategory = 
  | "compute"
  | "containers"
  | "database"
  | "storage"
  | "networking"
  | "security"
  | "analytics"
  | "integration"
  | "management"
  | "devops"
  | "governance"
  | "policies"
  | "boundaries"
  | "icons"
  | "text"
  | "annotations";

export interface AWSService {
  id: string;
  name: string;
  shortName: string;
  category: AWSCategory;
  color: string;
  description: string;
  // For diagram validation - what can this service connect to?
  canConnectTo?: string[];
  // For diagram validation - must be inside these container types
  mustBeInside?: string[];
  // Is this a container (VPC, Subnet, etc)?
  isContainer?: boolean;
  // Default configuration
  defaultConfig?: Record<string, unknown>;
}

// AWS Official Category Colors
export const AWS_CATEGORY_COLORS: Record<AWSCategory, string> = {
  compute: "#ED7100",
  containers: "#ED7100",
  database: "#3B48CC",
  storage: "#3F8624",
  networking: "#8C4FFF",
  security: "#DD344C",
  analytics: "#8C4FFF",
  integration: "#E7157B",
  management: "#E7157B",
  devops: "#3F8624",
  governance: "#232F3E",
  policies: "#7C3AED",
  boundaries: "#232F3E",
  icons: "#6B7280",
  text: "#9CA3AF",
  annotations: "#9CA3AF",
};

// Category metadata for the service picker
export const AWS_CATEGORIES: Array<{ id: AWSCategory; name: string; color: string; icon: string }> = [
  { id: "networking", name: "Networking", color: "#8C4FFF", icon: "Network" },
  { id: "compute", name: "Compute", color: "#ED7100", icon: "Server" },
  { id: "containers", name: "Containers", color: "#ED7100", icon: "Container" },
  { id: "database", name: "Database", color: "#3B48CC", icon: "Database" },
  { id: "storage", name: "Storage", color: "#3F8624", icon: "HardDrive" },
  { id: "security", name: "Security", color: "#DD344C", icon: "Shield" },
  { id: "policies", name: "Policies & Rules", color: "#7C3AED", icon: "FileText" },
  { id: "analytics", name: "Analytics", color: "#8C4FFF", icon: "BarChart3" },
  { id: "integration", name: "Integration", color: "#E7157B", icon: "Workflow" },
  { id: "devops", name: "DevOps & CI/CD", color: "#3F8624", icon: "GitBranch" },
  { id: "management", name: "Management", color: "#E7157B", icon: "Settings" },
  { id: "governance", name: "Governance", color: "#232F3E", icon: "Building" },
];

// ============================================================================
// CORE AWS SERVICES (~45 components)
// These are the services architects actually use daily
// ============================================================================
export const AWS_SERVICES: AWSService[] = [
  // ============ NETWORKING (10) ============
  {
    id: "vpc",
    name: "Amazon VPC",
    shortName: "VPC",
    category: "networking",
    color: "#8C4FFF",
    description: "Amazon VPC",
    isContainer: true,
    defaultConfig: { cidrBlock: "10.0.0.0/16" },
  },
  {
    id: "subnet-public",
    name: "Public Subnet",
    shortName: "Public Subnet",
    category: "networking",
    color: "#7AA116",
    description: "Public Subnet",
    isContainer: true,
    mustBeInside: ["vpc"],
    defaultConfig: { cidrBlock: "10.0.1.0/24", isPublic: true },
  },
  {
    id: "subnet-private",
    name: "Private Subnet",
    shortName: "Private Subnet",
    category: "networking",
    color: "#527FFF",
    description: "Private Subnet",
    isContainer: true,
    mustBeInside: ["vpc"],
    defaultConfig: { cidrBlock: "10.0.2.0/24", isPublic: false },
  },
  {
    id: "route-table",
    name: "Route Table",
    shortName: "Route Table",
    category: "networking",
    color: "#8C4FFF",
    description: "Route Table",
    mustBeInside: ["vpc"],
    canConnectTo: ["subnet-public", "subnet-private", "internet-gateway", "nat-gateway"],
  },
  {
    id: "nacl",
    name: "Network ACL",
    shortName: "NACL",
    category: "networking",
    color: "#8C4FFF",
    description: "Network ACL",
    mustBeInside: ["vpc"],
    canConnectTo: ["subnet-public", "subnet-private"],
  },
  {
    id: "security-group",
    name: "Security Group",
    shortName: "SG",
    category: "networking",
    color: "#DD344C",
    description: "Security Group",
    // NOTE: Security Groups are NOT containers - they are attachments/bindings to ENIs
    // Synced with aws-placement-rules.ts
    isContainer: false,
    mustBeInside: ["vpc"],
  },
  {
    id: "internet-gateway",
    name: "Internet Gateway",
    shortName: "IGW",
    category: "networking",
    color: "#8C4FFF",
    description: "Internet Gateway",
    canConnectTo: ["vpc", "route-table"],
  },
  {
    id: "nat-gateway",
    name: "NAT Gateway",
    shortName: "NAT GW",
    category: "networking",
    color: "#8C4FFF",
    description: "NAT Gateway",
    mustBeInside: ["subnet-public"],
    canConnectTo: ["route-table"],
  },
  {
    id: "vpc-peering",
    name: "VPC Peering",
    shortName: "VPC Peering",
    category: "networking",
    color: "#8C4FFF",
    description: "VPC Peering",
    canConnectTo: ["vpc"],
  },
  {
    id: "transit-gateway",
    name: "Transit Gateway",
    shortName: "TGW",
    category: "networking",
    color: "#8C4FFF",
    description: "Transit Gateway",
    canConnectTo: ["vpc", "vpc-peering"],
  },
  {
    id: "alb",
    name: "Application Load Balancer",
    shortName: "ALB",
    category: "networking",
    color: "#8C4FFF",
    description: "Application Load Balancer",
    // NOTE: ALB is a VPC-level resource that spans subnets (creates ENIs per AZ)
    // Synced with aws-placement-rules.ts
    mustBeInside: ["vpc"],
    canConnectTo: ["ec2", "ecs", "eks", "lambda", "auto-scaling"],
  },
  {
    id: "nlb",
    name: "Network Load Balancer",
    shortName: "NLB",
    category: "networking",
    color: "#8C4FFF",
    description: "Network Load Balancer",
    // NOTE: NLB is a VPC-level resource that spans subnets (creates ENIs per AZ)
    // Synced with aws-placement-rules.ts
    mustBeInside: ["vpc"],
    canConnectTo: ["ec2", "ecs", "eks", "auto-scaling"],
  },

  // ============ COMPUTE (5) ============
  {
    id: "ec2",
    name: "Amazon EC2",
    shortName: "EC2",
    category: "compute",
    color: "#ED7100",
    description: "Amazon EC2",
    mustBeInside: ["subnet-public", "subnet-private", "auto-scaling"],
    canConnectTo: ["rds", "aurora", "dynamodb", "s3", "elasticache", "efs", "ebs", "sqs", "sns"],
    defaultConfig: { instanceType: "t3.micro" },
  },
  {
    id: "auto-scaling",
    name: "Auto Scaling Group",
    shortName: "ASG",
    category: "compute",
    color: "#ED7100",
    description: "Auto Scaling Group",
    isContainer: true,
    mustBeInside: ["subnet-public", "subnet-private"],
    canConnectTo: ["alb", "nlb"],
  },
  {
    id: "lambda",
    name: "AWS Lambda",
    shortName: "Lambda",
    category: "compute",
    color: "#ED7100",
    description: "AWS Lambda",
    canConnectTo: ["rds", "aurora", "dynamodb", "s3", "elasticache", "sqs", "sns", "eventbridge"],
    defaultConfig: { runtime: "nodejs20.x", memory: 128 },
  },
  {
    id: "ebs",
    name: "Amazon EBS",
    shortName: "EBS",
    category: "compute",
    color: "#ED7100",
    description: "Amazon EBS",
    canConnectTo: ["ec2"],
  },
  {
    id: "efs",
    name: "Amazon EFS",
    shortName: "EFS",
    category: "storage",
    color: "#3F8624",
    description: "Amazon EFS",
    // NOTE: EFS is a Regional service - mount targets are in subnets
    // Synced with aws-placement-rules.ts
    mustBeInside: [],  // Regional service, not inside VPC
    canConnectTo: ["ec2", "ecs", "eks", "lambda"],
  },

  // ============ CONTAINERS (4) ============
  {
    id: "ecs",
    name: "Amazon ECS",
    shortName: "ECS",
    category: "containers",
    color: "#ED7100",
    description: "Amazon ECS",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["rds", "aurora", "dynamodb", "s3", "elasticache", "ecr"],
  },
  {
    id: "eks",
    name: "Amazon EKS",
    shortName: "EKS",
    category: "containers",
    color: "#ED7100",
    description: "Amazon EKS",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["rds", "aurora", "dynamodb", "s3", "elasticache", "ecr"],
  },
  {
    id: "fargate",
    name: "AWS Fargate",
    shortName: "Fargate",
    category: "containers",
    color: "#ED7100",
    description: "AWS Fargate",
    canConnectTo: ["rds", "aurora", "dynamodb", "s3", "ecr"],
  },
  {
    id: "ecr",
    name: "Amazon ECR",
    shortName: "ECR",
    category: "containers",
    color: "#ED7100",
    description: "Amazon ECR",
    canConnectTo: ["ecs", "eks", "fargate"],
  },

  // ============ DATABASE (6) ============
  {
    id: "rds",
    name: "Amazon RDS",
    shortName: "RDS",
    category: "database",
    color: "#3B48CC",
    description: "Amazon RDS",
    mustBeInside: ["subnet-private"],
    defaultConfig: { engine: "postgresql", instanceClass: "db.t3.micro", multiAZ: false },
  },
  {
    id: "aurora",
    name: "Amazon Aurora",
    shortName: "Aurora",
    category: "database",
    color: "#3B48CC",
    description: "Amazon Aurora",
    mustBeInside: ["subnet-private"],
    defaultConfig: { engine: "aurora-postgresql", multiAZ: true },
  },
  {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    shortName: "DynamoDB",
    category: "database",
    color: "#3B48CC",
    description: "Amazon DynamoDB",
    defaultConfig: { billingMode: "PAY_PER_REQUEST" },
  },
  {
    id: "elasticache",
    name: "Amazon ElastiCache",
    shortName: "ElastiCache",
    category: "database",
    color: "#3B48CC",
    description: "Amazon ElastiCache",
    mustBeInside: ["subnet-private"],
    defaultConfig: { engine: "redis" },
  },
  {
    id: "redshift",
    name: "Amazon Redshift",
    shortName: "Redshift",
    category: "database",
    color: "#3B48CC",
    description: "Amazon Redshift",
    mustBeInside: ["subnet-private"],
  },
  {
    id: "neptune",
    name: "Amazon Neptune",
    shortName: "Neptune",
    category: "database",
    color: "#3B48CC",
    description: "Amazon Neptune",
    mustBeInside: ["subnet-private"],
  },

  // ============ STORAGE (3) ============
  {
    id: "s3",
    name: "Amazon S3",
    shortName: "S3",
    category: "storage",
    color: "#3F8624",
    description: "Amazon S3",
    canConnectTo: ["cloudfront", "lambda", "eventbridge"],
    defaultConfig: { versioning: false },
  },
  {
    id: "glacier",
    name: "Amazon S3 Glacier",
    shortName: "Glacier",
    category: "storage",
    color: "#3F8624",
    description: "Amazon S3 Glacier",
    canConnectTo: ["s3"],
  },
  {
    id: "backup",
    name: "AWS Backup",
    shortName: "Backup",
    category: "storage",
    color: "#3F8624",
    description: "AWS Backup",
    canConnectTo: ["rds", "aurora", "dynamodb", "efs", "ebs", "s3"],
  },

  // ============ SECURITY (7) ============
  {
    id: "iam",
    name: "AWS IAM",
    shortName: "IAM",
    category: "security",
    color: "#DD344C",
    description: "AWS IAM",
  },
  {
    id: "kms",
    name: "AWS KMS",
    shortName: "KMS",
    category: "security",
    color: "#DD344C",
    description: "AWS KMS",
    canConnectTo: ["s3", "rds", "aurora", "ebs", "efs"],
  },
  {
    id: "secrets-manager",
    name: "AWS Secrets Manager",
    shortName: "Secrets Mgr",
    category: "security",
    color: "#DD344C",
    description: "AWS Secrets Manager",
    canConnectTo: ["rds", "aurora", "lambda"],
  },
  {
    id: "cognito",
    name: "Amazon Cognito",
    shortName: "Cognito",
    category: "security",
    color: "#DD344C",
    description: "Amazon Cognito",
    canConnectTo: ["api-gateway", "alb", "lambda"],
  },
  {
    id: "waf",
    name: "AWS WAF",
    shortName: "WAF",
    category: "security",
    color: "#DD344C",
    description: "AWS WAF",
    canConnectTo: ["cloudfront", "alb", "api-gateway"],
  },
  {
    id: "shield",
    name: "AWS Shield",
    shortName: "Shield",
    category: "security",
    color: "#DD344C",
    description: "AWS Shield",
    canConnectTo: ["cloudfront", "alb", "nlb"],
  },
  {
    id: "guardduty",
    name: "Amazon GuardDuty",
    shortName: "GuardDuty",
    category: "security",
    color: "#DD344C",
    description: "Amazon GuardDuty",
  },

  // ============ INTEGRATION (4) ============
  {
    id: "api-gateway",
    name: "Amazon API Gateway",
    shortName: "API Gateway",
    category: "integration",
    color: "#E7157B",
    description: "Amazon API Gateway",
    canConnectTo: ["lambda", "ec2", "ecs", "alb", "nlb"],
  },
  {
    id: "eventbridge",
    name: "Amazon EventBridge",
    shortName: "EventBridge",
    category: "integration",
    color: "#E7157B",
    description: "Amazon EventBridge",
    canConnectTo: ["lambda", "sqs", "sns", "api-gateway"],
  },
  {
    id: "sns",
    name: "Amazon SNS",
    shortName: "SNS",
    category: "integration",
    color: "#E7157B",
    description: "Amazon SNS",
    canConnectTo: ["lambda", "sqs", "ec2"],
  },
  {
    id: "sqs",
    name: "Amazon SQS",
    shortName: "SQS",
    category: "integration",
    color: "#E7157B",
    description: "Amazon SQS",
    canConnectTo: ["lambda", "ec2", "ecs"],
  },

  // ============ MANAGEMENT (4) ============
  {
    id: "cloudwatch",
    name: "Amazon CloudWatch",
    shortName: "CloudWatch",
    category: "management",
    color: "#E7157B",
    description: "Amazon CloudWatch",
  },
  {
    id: "cloudtrail",
    name: "AWS CloudTrail",
    shortName: "CloudTrail",
    category: "management",
    color: "#E7157B",
    description: "AWS CloudTrail",
  },
  {
    id: "systems-manager",
    name: "AWS Systems Manager",
    shortName: "SSM",
    category: "management",
    color: "#E7157B",
    description: "AWS Systems Manager",
    canConnectTo: ["ec2", "ecs", "eks"],
  },
  {
    id: "config",
    name: "AWS Config",
    shortName: "Config",
    category: "management",
    color: "#E7157B",
    description: "AWS Config",
  },

  // ============ ADDITIONAL NETWORKING ============
  {
    id: "route53",
    name: "Amazon Route 53",
    shortName: "Route 53",
    category: "networking",
    color: "#8C4FFF",
    description: "Amazon Route 53",
    canConnectTo: ["alb", "nlb", "cloudfront", "api-gateway", "s3"],
  },
  {
    id: "cloudfront",
    name: "Amazon CloudFront",
    shortName: "CloudFront",
    category: "networking",
    color: "#8C4FFF",
    description: "Amazon CloudFront",
    canConnectTo: ["s3", "alb", "api-gateway", "lambda"],
  },

  // ============ ADDITIONAL NETWORKING (DR/HA) ============
  {
    id: "global-accelerator",
    name: "AWS Global Accelerator",
    shortName: "Global Accelerator",
    category: "networking",
    color: "#8C4FFF",
    description: "AWS Global Accelerator",
    canConnectTo: ["alb", "nlb", "ec2", "elastic-ip"],
  },
  {
    id: "vpn-gateway",
    name: "AWS VPN Gateway",
    shortName: "VPN GW",
    category: "networking",
    color: "#8C4FFF",
    description: "AWS VPN Gateway",
    mustBeInside: ["vpc"],
    canConnectTo: ["transit-gateway", "route-table"],
  },
  {
    id: "direct-connect",
    name: "AWS Direct Connect",
    shortName: "Direct Connect",
    category: "networking",
    color: "#8C4FFF",
    description: "AWS Direct Connect",
    canConnectTo: ["vpc", "transit-gateway"],
  },
  {
    id: "privatelink",
    name: "AWS PrivateLink",
    shortName: "PrivateLink",
    category: "networking",
    color: "#8C4FFF",
    description: "AWS PrivateLink",
    mustBeInside: ["vpc"],
    canConnectTo: ["s3", "dynamodb", "api-gateway"],
  },
  {
    id: "elastic-ip",
    name: "Elastic IP",
    shortName: "EIP",
    category: "networking",
    color: "#8C4FFF",
    description: "Elastic IP",
    canConnectTo: ["ec2", "nat-gateway", "nlb"],
  },

  // ============ DEVOPS & CI/CD (6) ============
  {
    id: "codecommit",
    name: "AWS CodeCommit",
    shortName: "CodeCommit",
    category: "devops",
    color: "#3F8624",
    description: "AWS CodeCommit",
    canConnectTo: ["codepipeline", "codebuild"],
  },
  {
    id: "codepipeline",
    name: "AWS CodePipeline",
    shortName: "CodePipeline",
    category: "devops",
    color: "#3F8624",
    description: "AWS CodePipeline",
    canConnectTo: ["codecommit", "codebuild", "codedeploy", "s3", "ecr", "ecs", "eks", "lambda"],
  },
  {
    id: "codebuild",
    name: "AWS CodeBuild",
    shortName: "CodeBuild",
    category: "devops",
    color: "#3F8624",
    description: "AWS CodeBuild",
    canConnectTo: ["codecommit", "s3", "ecr", "codepipeline"],
  },
  {
    id: "codedeploy",
    name: "AWS CodeDeploy",
    shortName: "CodeDeploy",
    category: "devops",
    color: "#3F8624",
    description: "AWS CodeDeploy",
    canConnectTo: ["ec2", "ecs", "lambda", "auto-scaling", "s3"],
  },
  {
    id: "codeartifact",
    name: "AWS CodeArtifact",
    shortName: "CodeArtifact",
    category: "devops",
    color: "#3F8624",
    description: "AWS CodeArtifact",
    canConnectTo: ["codebuild", "codepipeline"],
  },
  {
    id: "cloud9",
    name: "AWS Cloud9",
    shortName: "Cloud9",
    category: "devops",
    color: "#3F8624",
    description: "AWS Cloud9",
    canConnectTo: ["codecommit", "lambda"],
  },

  // ============ ANALYTICS & STREAMING (8) ============
  {
    id: "kinesis-streams",
    name: "Amazon Kinesis Data Streams",
    shortName: "Kinesis Streams",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon Kinesis Data Streams",
    canConnectTo: ["lambda", "kinesis-firehose", "kinesis-analytics"],
  },
  {
    id: "kinesis-firehose",
    name: "Amazon Kinesis Firehose",
    shortName: "Firehose",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon Kinesis Firehose",
    canConnectTo: ["s3", "redshift", "opensearch", "splunk"],
  },
  {
    id: "kinesis-analytics",
    name: "Amazon Kinesis Analytics",
    shortName: "Kinesis Analytics",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon Kinesis Analytics",
    canConnectTo: ["kinesis-streams", "kinesis-firehose", "lambda"],
  },
  {
    id: "msk",
    name: "Amazon MSK",
    shortName: "MSK (Kafka)",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon MSK",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["lambda", "ecs", "eks", "ec2"],
  },
  {
    id: "athena",
    name: "Amazon Athena",
    shortName: "Athena",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon Athena",
    canConnectTo: ["s3", "glue"],
  },
  {
    id: "glue",
    name: "AWS Glue",
    shortName: "Glue",
    category: "analytics",
    color: "#8C4FFF",
    description: "AWS Glue",
    canConnectTo: ["s3", "rds", "redshift", "athena"],
  },
  {
    id: "quicksight",
    name: "Amazon QuickSight",
    shortName: "QuickSight",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon QuickSight",
    canConnectTo: ["athena", "redshift", "rds", "s3"],
  },
  {
    id: "opensearch",
    name: "Amazon OpenSearch",
    shortName: "OpenSearch",
    category: "analytics",
    color: "#8C4FFF",
    description: "Amazon OpenSearch",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["kinesis-firehose", "lambda", "cloudwatch"],
  },

  // ============ ADDITIONAL SECURITY (8) ============
  {
    id: "iam-role",
    name: "IAM Role",
    shortName: "IAM Role",
    category: "security",
    color: "#DD344C",
    description: "IAM Role",
    canConnectTo: ["ec2", "lambda", "ecs", "eks", "codepipeline"],
  },
  {
    id: "iam-policy",
    name: "IAM Policy",
    shortName: "IAM Policy",
    category: "security",
    color: "#DD344C",
    description: "IAM Policy",
    canConnectTo: ["iam-role", "iam"],
  },
  {
    id: "permission-boundary",
    name: "Permission Boundary",
    shortName: "Perm Boundary",
    category: "security",
    color: "#DD344C",
    description: "Permission Boundary",
    canConnectTo: ["iam-role", "iam"],
  },
  {
    id: "acm",
    name: "AWS Certificate Manager",
    shortName: "ACM",
    category: "security",
    color: "#DD344C",
    description: "AWS Certificate Manager",
    canConnectTo: ["alb", "nlb", "cloudfront", "api-gateway"],
  },
  {
    id: "inspector",
    name: "Amazon Inspector",
    shortName: "Inspector",
    category: "security",
    color: "#DD344C",
    description: "Amazon Inspector",
    canConnectTo: ["ec2", "ecr", "lambda"],
  },
  {
    id: "macie",
    name: "Amazon Macie",
    shortName: "Macie",
    category: "security",
    color: "#DD344C",
    description: "Amazon Macie",
    canConnectTo: ["s3"],
  },
  {
    id: "security-hub",
    name: "AWS Security Hub",
    shortName: "Security Hub",
    category: "security",
    color: "#DD344C",
    description: "AWS Security Hub",
    canConnectTo: ["guardduty", "inspector", "macie", "config"],
  },
  {
    id: "detective",
    name: "Amazon Detective",
    shortName: "Detective",
    category: "security",
    color: "#DD344C",
    description: "Amazon Detective",
    canConnectTo: ["guardduty", "cloudtrail"],
  },
  {
    id: "iam-user",
    name: "IAM User",
    shortName: "IAM User",
    category: "security",
    color: "#DD344C",
    description: "IAM User",
    canConnectTo: ["iam-policy", "iam-group"],
  },
  {
    id: "iam-group",
    name: "IAM Group",
    shortName: "IAM Group",
    category: "security",
    color: "#DD344C",
    description: "IAM Group",
    canConnectTo: ["iam-policy", "iam-user"],
  },
  {
    id: "resource-policy",
    name: "Resource Policy",
    shortName: "Resource Policy",
    category: "security",
    color: "#DD344C",
    description: "Resource Policy",
    canConnectTo: ["s3", "sqs", "sns", "kms", "secrets-manager", "ecr", "lambda"],
  },
  {
    id: "trust-policy",
    name: "Trust Policy",
    shortName: "Trust Policy",
    category: "security",
    color: "#DD344C",
    description: "Trust Policy",
    canConnectTo: ["iam-role"],
  },
  {
    id: "identity-provider",
    name: "Identity Provider",
    shortName: "IdP",
    category: "security",
    color: "#DD344C",
    description: "Identity Provider",
    canConnectTo: ["iam-role", "cognito"],
  },
  {
    id: "iam-identity-center",
    name: "IAM Identity Center",
    shortName: "IAM IC (SSO)",
    category: "security",
    color: "#DD344C",
    description: "IAM Identity Center",
    canConnectTo: ["organizations", "identity-provider"],
  },

  // ============ ADDITIONAL STORAGE (3) ============
  {
    id: "fsx",
    name: "Amazon FSx",
    shortName: "FSx",
    category: "storage",
    color: "#3F8624",
    description: "Amazon FSx",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["ec2", "ecs", "eks"],
  },
  {
    id: "storage-gateway",
    name: "AWS Storage Gateway",
    shortName: "Storage GW",
    category: "storage",
    color: "#3F8624",
    description: "AWS Storage Gateway",
    canConnectTo: ["s3", "glacier"],
  },
  {
    id: "datasync",
    name: "AWS DataSync",
    shortName: "DataSync",
    category: "storage",
    color: "#3F8624",
    description: "AWS DataSync",
    canConnectTo: ["s3", "efs", "fsx"],
  },

  // ============ ADDITIONAL DATABASE (3) ============
  {
    id: "documentdb",
    name: "Amazon DocumentDB",
    shortName: "DocumentDB",
    category: "database",
    color: "#3B48CC",
    description: "Amazon DocumentDB",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["lambda", "ecs", "eks", "ec2"],
  },
  {
    id: "memorydb",
    name: "Amazon MemoryDB",
    shortName: "MemoryDB",
    category: "database",
    color: "#3B48CC",
    description: "Amazon MemoryDB",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["lambda", "ecs", "eks", "ec2"],
  },
  {
    id: "rds-replica",
    name: "RDS Read Replica",
    shortName: "Read Replica",
    category: "database",
    color: "#3B48CC",
    description: "RDS Read Replica",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["rds", "aurora"],
  },

  // ============ GOVERNANCE & ORGANIZATIONS (6) ============
  {
    id: "organizations",
    name: "AWS Organizations",
    shortName: "Organizations",
    category: "governance",
    color: "#232F3E",
    description: "AWS Organizations",
    canConnectTo: ["scp", "control-tower"],
  },
  {
    id: "scp",
    name: "Service Control Policy",
    shortName: "SCP",
    category: "governance",
    color: "#232F3E",
    description: "Service Control Policy",
    canConnectTo: ["organizations"],
  },
  {
    id: "control-tower",
    name: "AWS Control Tower",
    shortName: "Control Tower",
    category: "governance",
    color: "#232F3E",
    description: "AWS Control Tower",
    canConnectTo: ["organizations", "scp"],
  },
  {
    id: "service-catalog",
    name: "AWS Service Catalog",
    shortName: "Service Catalog",
    category: "governance",
    color: "#232F3E",
    description: "AWS Service Catalog",
    canConnectTo: ["cloudformation"],
  },
  {
    id: "license-manager",
    name: "AWS License Manager",
    shortName: "License Mgr",
    category: "governance",
    color: "#232F3E",
    description: "AWS License Manager",
    canConnectTo: ["ec2", "rds"],
  },
  {
    id: "resource-groups",
    name: "AWS Resource Groups",
    shortName: "Resource Groups",
    category: "governance",
    color: "#232F3E",
    description: "AWS Resource Groups",
  },

  // ============ ADDITIONAL MANAGEMENT (6) ============
  {
    id: "xray",
    name: "AWS X-Ray",
    shortName: "X-Ray",
    category: "management",
    color: "#E7157B",
    description: "AWS X-Ray",
    canConnectTo: ["lambda", "ecs", "eks", "api-gateway"],
  },
  {
    id: "cloudwatch-logs",
    name: "CloudWatch Logs",
    shortName: "CW Logs",
    category: "management",
    color: "#E7157B",
    description: "CloudWatch Logs",
    canConnectTo: ["lambda", "ecs", "ec2", "rds"],
  },
  {
    id: "cloudwatch-alarms",
    name: "CloudWatch Alarms",
    shortName: "CW Alarms",
    category: "management",
    color: "#E7157B",
    description: "CloudWatch Alarms",
    canConnectTo: ["sns", "lambda", "auto-scaling"],
  },
  {
    id: "cloudformation",
    name: "AWS CloudFormation",
    shortName: "CloudFormation",
    category: "management",
    color: "#E7157B",
    description: "AWS CloudFormation",
    canConnectTo: ["s3", "codepipeline"],
  },
  {
    id: "health-dashboard",
    name: "AWS Health Dashboard",
    shortName: "Health",
    category: "management",
    color: "#E7157B",
    description: "AWS Health Dashboard",
    canConnectTo: ["eventbridge", "sns"],
  },
  {
    id: "trusted-advisor",
    name: "AWS Trusted Advisor",
    shortName: "Trusted Advisor",
    category: "management",
    color: "#E7157B",
    description: "AWS Trusted Advisor",
  },

  // ============ ADDITIONAL INTEGRATION (4) ============
  {
    id: "step-functions",
    name: "AWS Step Functions",
    shortName: "Step Functions",
    category: "integration",
    color: "#E7157B",
    description: "AWS Step Functions",
    canConnectTo: ["lambda", "ecs", "sns", "sqs", "dynamodb"],
  },
  {
    id: "appsync",
    name: "AWS AppSync",
    shortName: "AppSync",
    category: "integration",
    color: "#E7157B",
    description: "AWS AppSync",
    canConnectTo: ["dynamodb", "lambda", "rds", "opensearch"],
  },
  {
    id: "mq",
    name: "Amazon MQ",
    shortName: "MQ",
    category: "integration",
    color: "#E7157B",
    description: "Amazon MQ",
    mustBeInside: ["subnet-private"],
    canConnectTo: ["ec2", "ecs", "lambda"],
  },
  {
    id: "ses",
    name: "Amazon SES",
    shortName: "SES",
    category: "integration",
    color: "#E7157B",
    description: "Amazon SES",
    canConnectTo: ["lambda", "sns"],
  },

  // ============ ADDITIONAL COMPUTE (2) ============
  {
    id: "batch",
    name: "AWS Batch",
    shortName: "Batch",
    category: "compute",
    color: "#ED7100",
    description: "AWS Batch",
    canConnectTo: ["s3", "efs", "ecr"],
  },
  {
    id: "lightsail",
    name: "Amazon Lightsail",
    shortName: "Lightsail",
    category: "compute",
    color: "#ED7100",
    description: "Amazon Lightsail",
    canConnectTo: ["s3", "rds"],
  },

  // ============ POLICIES & RULES (15) ============
  // All policy types that can be visualized in architecture diagrams
  {
    id: "s3-lifecycle-policy",
    name: "S3 Lifecycle Policy",
    shortName: "S3 Lifecycle",
    category: "policies",
    color: "#7C3AED",
    description: "S3 Lifecycle Policy",
    canConnectTo: ["s3", "glacier"],
  },
  {
    id: "s3-bucket-policy",
    name: "S3 Bucket Policy",
    shortName: "Bucket Policy",
    category: "policies",
    color: "#7C3AED",
    description: "S3 Bucket Policy",
    canConnectTo: ["s3"],
  },
  {
    id: "iam-identity-policy",
    name: "IAM Identity Policy",
    shortName: "Identity Policy",
    category: "policies",
    color: "#7C3AED",
    description: "IAM Identity Policy",
    canConnectTo: ["iam-role", "iam-user", "iam-group"],
  },
  {
    id: "iam-trust-policy",
    name: "IAM Trust Policy",
    shortName: "Trust Policy",
    category: "policies",
    color: "#7C3AED",
    description: "Trust Policy",
    canConnectTo: ["iam-role"],
  },
  {
    id: "resource-based-policy",
    name: "Resource-Based Policy",
    shortName: "Resource Policy",
    category: "policies",
    color: "#7C3AED",
    description: "Resource-Based Policy",
    canConnectTo: ["sqs", "sns", "kms", "secrets-manager", "ecr", "lambda", "api-gateway"],
  },
  {
    id: "vpc-endpoint-policy",
    name: "VPC Endpoint Policy",
    shortName: "Endpoint Policy",
    category: "policies",
    color: "#7C3AED",
    description: "VPC Endpoint Policy",
    canConnectTo: ["privatelink", "s3", "dynamodb"],
  },
  {
    id: "backup-policy",
    name: "Backup Policy",
    shortName: "Backup Policy",
    category: "policies",
    color: "#7C3AED",
    description: "Backup Policy",
    canConnectTo: ["backup", "rds", "dynamodb", "efs", "ec2"],
  },
  {
    id: "scaling-policy",
    name: "Scaling Policy",
    shortName: "Scaling Policy",
    category: "policies",
    color: "#7C3AED",
    description: "Scaling Policy",
    canConnectTo: ["auto-scaling", "ecs", "dynamodb"],
  },
  {
    id: "dlm-policy",
    name: "DLM Lifecycle Policy",
    shortName: "DLM Policy",
    category: "policies",
    color: "#7C3AED",
    description: "DLM Lifecycle Policy",
    canConnectTo: ["ebs", "ec2"],
  },
  {
    id: "ecr-lifecycle-policy",
    name: "ECR Lifecycle Policy",
    shortName: "ECR Lifecycle",
    category: "policies",
    color: "#7C3AED",
    description: "ECR Lifecycle Policy",
    canConnectTo: ["ecr"],
  },
  // Note: SCP is already defined in Governance category as "scp"
  {
    id: "permission-boundary-policy",
    name: "Permission Boundary",
    shortName: "Perm Boundary",
    category: "policies",
    color: "#7C3AED",
    description: "Permission Boundary",
    canConnectTo: ["iam-role", "iam-user"],
  },
  {
    id: "rds-parameter-group",
    name: "RDS Parameter Group",
    shortName: "Param Group",
    category: "policies",
    color: "#7C3AED",
    description: "RDS Parameter Group",
    canConnectTo: ["rds", "aurora"],
  },
  {
    id: "elasticache-parameter-group",
    name: "ElastiCache Parameter Group",
    shortName: "Cache Params",
    category: "policies",
    color: "#7C3AED",
    description: "ElastiCache Parameter Group",
    canConnectTo: ["elasticache"],
  },
  {
    id: "waf-rules",
    name: "WAF Rules & Rule Groups",
    shortName: "WAF Rules",
    category: "policies",
    color: "#7C3AED",
    description: "WAF Rules & Rule Groups",
    canConnectTo: ["waf", "alb", "cloudfront", "api-gateway"],
  },

  // Custom service added via API
  {
    id: "emr",
    name: "Elastic Map Reduce",
    shortName: "EMR",
    category: "integration",
    color: "#E7157B",
    description: "Elastic Map Reduce",
  },

  // Custom service added via API
  {
    id: "ebsk",
    name: "Elastic Beanstalk",
    shortName: "EBSK",
    category: "compute",
    color: "#ED7100",
    description: "Custom compute service",
  },

  // ============ AWS BOUNDARIES (3) ============
  // Container elements for organizing architecture - now in Networking
  {
    id: "aws-cloud",
    name: "AWS Cloud",
    shortName: "AWS Cloud",
    category: "networking",
    color: "#232F3E",
    description: "AWS Cloud boundary - top-level container for all AWS resources",
    isContainer: true,
  },
  {
    id: "region",
    name: "Region",
    shortName: "Region",
    category: "networking",
    color: "#147EBA",
    description: "AWS Region boundary - contains availability zones and resources",
    isContainer: true,
    mustBeInside: ["aws-cloud"],
  },
  {
    id: "availability-zone",
    name: "Availability Zone",
    shortName: "AZ",
    category: "networking",
    color: "#147EBA",
    description: "Availability Zone boundary - isolated location within a region",
    isContainer: true,
    mustBeInside: ["region"],
  },

  // ============ GENERAL ICONS (12) ============
  // Visual elements representing users, devices, and external systems
  {
    id: "icon-user",
    name: "User",
    shortName: "User",
    category: "icons",
    color: "#6B7280",
    description: "Single user/client accessing the system",
    canConnectTo: ["cloudfront", "route53", "alb", "nlb", "api-gateway", "cognito"],
  },
  {
    id: "icon-users",
    name: "Users",
    shortName: "Users",
    category: "icons",
    color: "#6B7280",
    description: "Multiple users/clients accessing the system",
    canConnectTo: ["cloudfront", "route53", "alb", "nlb", "api-gateway", "cognito"],
  },
  {
    id: "icon-mobile",
    name: "Mobile",
    shortName: "Mobile",
    category: "icons",
    color: "#6B7280",
    description: "Mobile device client",
    canConnectTo: ["cloudfront", "route53", "alb", "api-gateway", "cognito", "appsync"],
  },
  {
    id: "icon-laptop",
    name: "Laptop",
    shortName: "Laptop",
    category: "icons",
    color: "#6B7280",
    description: "Laptop/computer client",
    canConnectTo: ["cloudfront", "route53", "alb", "api-gateway", "cognito"],
  },
  {
    id: "icon-desktop",
    name: "Desktop",
    shortName: "Desktop",
    category: "icons",
    color: "#6B7280",
    description: "Desktop computer client",
    canConnectTo: ["cloudfront", "route53", "alb", "api-gateway", "cognito"],
  },
  {
    id: "icon-internet",
    name: "Internet",
    shortName: "Internet",
    category: "icons",
    color: "#6B7280",
    description: "Public internet/external network",
    canConnectTo: ["cloudfront", "route53", "internet-gateway", "alb", "nlb", "api-gateway"],
  },
  {
    id: "icon-cloud",
    name: "Cloud",
    shortName: "Cloud",
    category: "icons",
    color: "#6B7280",
    description: "External cloud service or third-party cloud",
    canConnectTo: ["vpc", "direct-connect", "vpn-gateway", "transit-gateway"],
  },
  {
    id: "icon-corporate",
    name: "Corporate",
    shortName: "Corporate",
    category: "icons",
    color: "#6B7280",
    description: "Corporate network/data center",
    canConnectTo: ["direct-connect", "vpn-gateway", "transit-gateway"],
  },
  {
    id: "icon-on-prem",
    name: "On-Premises",
    shortName: "On-Prem",
    category: "icons",
    color: "#6B7280",
    description: "On-premises data center or infrastructure",
    canConnectTo: ["direct-connect", "vpn-gateway", "storage-gateway", "datasync"],
  },
  {
    id: "icon-server",
    name: "Server",
    shortName: "Server",
    category: "icons",
    color: "#6B7280",
    description: "Generic server or external system",
    canConnectTo: ["direct-connect", "vpn-gateway", "transit-gateway"],
  },
  {
    id: "icon-database",
    name: "Database",
    shortName: "Database",
    category: "icons",
    color: "#6B7280",
    description: "External database or data source",
    canConnectTo: ["direct-connect", "vpn-gateway", "datasync"],
  },
  {
    id: "icon-security",
    name: "Security",
    shortName: "Security",
    category: "icons",
    color: "#6B7280",
    description: "Security element or external security service",
    canConnectTo: ["waf", "shield", "guardduty", "cognito"],
  },

  // ============ TEXT ELEMENTS (2) ============
  // Documentation and notes within diagrams
  {
    id: "textbox",
    name: "Text Box",
    shortName: "Text",
    category: "text",
    color: "#9CA3AF",
    description: "Text box for labels and descriptions",
  },
  {
    id: "note",
    name: "Note",
    shortName: "Note",
    category: "text",
    color: "#FCD34D",
    description: "Sticky note for annotations and comments",
  },

  // ============ ARCHITECTURE ANNOTATIONS (7) ============
  // Documentation elements for policies, flows, and metadata
  {
    id: "legend",
    name: "Legend",
    shortName: "Legend",
    category: "annotations",
    color: "#9CA3AF",
    description: "Color key and ownership legend for the diagram",
  },
  {
    id: "lifecycle-annotation",
    name: "Lifecycle Policy",
    shortName: "Lifecycle",
    category: "annotations",
    color: "#9CA3AF",
    description: "S3/backup lifecycle rules annotation",
    canConnectTo: ["s3", "glacier", "backup"],
  },
  {
    id: "pipeline-annotation",
    name: "CI/CD Pipeline",
    shortName: "Pipeline",
    category: "annotations",
    color: "#9CA3AF",
    description: "CI/CD pipeline stages annotation",
    canConnectTo: ["codepipeline", "codebuild", "codedeploy", "codecommit"],
  },
  {
    id: "scaling-annotation",
    name: "Scaling Policy",
    shortName: "Scaling",
    category: "annotations",
    color: "#9CA3AF",
    description: "Auto scaling configuration annotation",
    canConnectTo: ["auto-scaling", "ecs", "eks", "dynamodb"],
  },
  {
    id: "backup-annotation",
    name: "Backup Plan",
    shortName: "Backup",
    category: "annotations",
    color: "#9CA3AF",
    description: "Backup schedule and retention annotation",
    canConnectTo: ["backup", "rds", "dynamodb", "efs", "ebs"],
  },
  {
    id: "dataflow-annotation",
    name: "Data Flow",
    shortName: "Data Flow",
    category: "annotations",
    color: "#9CA3AF",
    description: "Traffic and data flow annotation",
  },
  {
    id: "iam-policy-annotation",
    name: "IAM Policy Document",
    shortName: "IAM Doc",
    category: "annotations",
    color: "#9CA3AF",
    description: "IAM policy document annotation",
    canConnectTo: ["iam", "iam-role", "iam-policy", "iam-user", "iam-group"],
  },
];

// Helper functions
export function getServiceById(id: string): AWSService | undefined {
  return AWS_SERVICES.find((s) => s.id === id);
}

export function getServicesByCategory(category: AWSCategory): AWSService[] {
  return AWS_SERVICES.filter((s) => s.category === category);
}

export function searchServices(query: string): AWSService[] {
  const q = query.toLowerCase();
  return AWS_SERVICES.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.shortName.toLowerCase().includes(q) ||
      s.id.includes(q) ||
      s.description.toLowerCase().includes(q)
  );
}

// Get container services (VPC, Subnet, etc.)
export function getContainerServices(): AWSService[] {
  return AWS_SERVICES.filter((s) => s.isContainer);
}

// Get non-container services (EC2, RDS, etc.)
export function getResourceServices(): AWSService[] {
  return AWS_SERVICES.filter((s) => !s.isContainer);
}
